ProjectZ/Models/CompanyViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ProjectZ.BLL.Enums;
using ProjectZ.BLL.Models;

namespace ProjectZ.Models
{
    public class CompanyViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public LegalStatus LegalStatus { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

ProjectZ/Models/EmployeeViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using ProjectZ.BLL.Enums;
using ProjectZ.BLL.Models;

namespace ProjectZ.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public string MiddleName { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public DateTime HiringDate { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public WorkingPosition? Position { get; set; }
        [Required(ErrorMessage = "This field cannot be empty")]
        public int CompanyId { get; set; }
        public Company Company { get; set; }
    }
}

ProjectZ/Models/ErrorViewModel.cs
namespace ProjectZ.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectZ/Controllers/CompaniesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectZ.BLL.Interfaces;
using ProjectZ.BLL.Models;
using ProjectZ.Mapper;
using ProjectZ.Models;

namespace ProjectZ.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEntityService<Company> _companyService;
        private readonly CustomViewModelMapper _mapper;
        public CompaniesController(IEntityService<Company> companyService, 
            ILogger<HomeController> logger, CustomViewModelMapper mapper)
        {
            _mapper = mapper;
            _logger = logger;
            _companyService = companyService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var companies =
                    _mapper.MapCompaniesToCompaniesViewModel(await _companyService.GetAllAsync());
                return View(companies);
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                return View(id.HasValue
                    ? _mapper.MapCompanyToCompanyViewModel(_companyService.GetEntityById(id.Value))
                    : new CompanyViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Edit(CompanyViewModel companyViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(companyViewModel);

                if (companyViewModel.Id != 0)
                    _companyService.Update(_mapper.MapCompanySqlModelToCompany(companyViewModel));
                else
                    _companyService.Create(_mapper.MapCompanySqlModelToCompany(companyViewModel));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _companyService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectZ/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using ProjectZ.BLL.Interfaces;
using ProjectZ.BLL.Models;
using ProjectZ.Mapper;
using ProjectZ.Models;

namespace ProjectZ.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEntityService<Employee> _employeeService;
        private readonly IEntityService<Company> _companyService;
        private readonly CustomViewModelMapper _mapper;
        public EmployeesController(IEntityService<Employee> employeeService, IEntityService<Company> companyService,
            ILogger<HomeController> logger, CustomViewModelMapper mapper)
        {
            _companyService = companyService;
            _mapper = mapper;
            _logger = logger;
            _employeeService = employeeService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var employees =
                    _mapper.MapEmployeesToEmployeesViewModel(await _employeeService.GetAllAsync());
                return View(employees);
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                ViewBag.Companies = _mapper.MapCompaniesToCompaniesViewModel(await _companyService.GetAllAsync());
                return View(id.HasValue
                    ? _mapper.MapEmployeeToEmployeeViewModel(_employeeService.GetEntityById(id.Value))
                    : new EmployeeViewModel());
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeViewModel employeeViewModel)
        {
            try
            {
                ViewBag.Companies = _mapper.MapCompaniesToCompaniesViewModel(await _companyService.GetAllAsync());
                if (!ModelState.IsValid)
                    return View(employeeViewModel);

                if (employeeViewModel.Id != 0)
                    _employeeService.Update(_mapper.MapEmployeeSqlModelToEmployee(employeeViewModel));
                else
                    _employeeService.Create(_mapper.MapEmployeeSqlModelToEmployee(employeeViewModel));

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _employeeService.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.LogError($"Method didn't work({e.Message}), {e.TargetSite}, {DateTime.Now}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ProjectZ/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectZ.Models;
using System.Diagnostics;

namespace ProjectZ.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectZ/Views/Companies/Edit.cshtml
@using ProjectZ.BLL.Enums
@{
}

@model CompanyViewModel


<div class="container">
    @if (Model.Id != 0)
    {
        <h2>Edit</h2>
    }
    else
    {
        <h2>Create</h2>
    }
    <form asp-controller="Companies" asp-action="Edit" method="post">
        <div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
        <div class="form-group">
            <label asp-for="Name">Name:</label>
            <input asp-for="Name" type="text" class="form-control" id="usr">
            <span class="alert-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="LegalStatus">Legal status:</label>
            <select asp-for="LegalStatus" class="form-control" id="sel1">
                <option selected value="">Choose...</option>
                <option value="@LegalStatus.ZAO">@LegalStatus.ZAO.ToString()</option>
                <option value="@LegalStatus.OAO">@LegalStatus.OAO.ToString()</option>
                <option value="@LegalStatus.ODO">@LegalStatus.ODO.ToString()</option>
                <option value="@LegalStatus.OOO">@LegalStatus.OOO.ToString()</option>
            </select>
            <span class="alert-danger" asp-validation-for="LegalStatus"></span>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-9 text-secondary">
                <button type="submit" class="btn btn-outline-primary px-4">Save</button>
                <a type="button" class="btn btn-outline-danger px-4" asp-action="Index">Close</a>
            </div>
        </div>
    </form>
</div>

ProjectZ/Views/Companies/Index.cshtml
@{
}

@model IEnumerable<CompanyViewModel>

<div class="container">
    <h2>Companies</h2>
    <div class="pb-2">
        <a asp-controller="Companies" asp-action="Edit"
           type="button" class="btn btn-primary">
            Create new company
        </a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Company name</th>
                <th>Legal status</th>
                <th>Number of employees</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var company in Model)
            {
                <tr>
                    <td>@company.Id</td>
                    <td>@company.Name</td>
                    <td>"@company.LegalStatus.ToString()"</td>
                    <td>"@company.Employees.Count()"</td>
                    <td>
                        <div class="row">
                            <div>
                                <a asp-controller="Companies" asp-action="Edit"
                                   asp-route-id="@company.Id" type="button" class="btn btn-success">
                                    Edit
                                </a>
                            </div>
                            <div class="pl-2">
                                <a asp-controller="Companies" asp-action="Delete"
                                   asp-route-id="@company.Id" type="button" class="btn btn-dark">
                                    Delete
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ProjectZ/Views/Employees/Edit.cshtml
@using ProjectZ.BLL.Enums
@{
  
    IEnumerable<CompanyViewModel> companies = ViewBag.Companies;
}

@model EmployeeViewModel


<div class="container">
    @if (Model.Id != 0)
    {
        <h2>Edit</h2>
    }
    else
    {
        <h2>Create</h2>
    }
<form asp-controller="Employees" asp-action="Edit" method="post">
    <div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name:</label>
        <input asp-for="FirstName" type="text" class="form-control">
        <span class="alert-danger" asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName">Last Name:</label>
        <input asp-for="LastName" type="text" class="form-control">
        <span class="alert-danger" asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="MiddleName">Middle Name:</label>
        <input asp-for="MiddleName" type="text" class="form-control">
        <span class="alert-danger" asp-validation-for="MiddleName"></span>
    </div>
    <div class="form-group">
        <label asp-for="HiringDate">Hiring Date:</label>
        <input asp-for="HiringDate" id="date" class="form-control" type="date">
        <span class="alert-danger" asp-validation-for="HiringDate"></span>
    </div>
    <div class="form-group">
        <label asp-for="Position">Position:</label>
        <select asp-for="Position" class="form-control">
            <option selected value="">Choose...</option>
            <option value="@WorkingPosition.Manager">@WorkingPosition.Manager.ToString()</option>
            <option value="@WorkingPosition.Developer">@WorkingPosition.Developer.ToString()</option>
            <option value="@WorkingPosition.BusinessAnalyst">@WorkingPosition.BusinessAnalyst.ToString()</option>
            <option value="@WorkingPosition.Tester">@WorkingPosition.Tester.ToString()</option>
        </select>
        <span class="alert-danger" asp-validation-for="Position"></span>
    </div>
    <div class="form-group">
        <label asp-for="CompanyId">Legal status:</label>
        <select asp-for="CompanyId" class="form-control" id="sel1">
            <option selected value="">Choose...</option>
            @foreach (var company in companies)
            {
                <option value="@company.Id">@company.Name</option>
            }
        </select>
        <span class="alert-danger" asp-validation-for="CompanyId"></span>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-9 text-secondary">
            <button type="submit" class="btn btn-outline-primary px-4">Save</button>
            <a type="button" class="btn btn-outline-danger px-4" asp-action="Index">Close</a>
        </div>
    </div>
</form>
</div>

ProjectZ/Views/Employees/Index.cshtml
@model IEnumerable<EmployeeViewModel>

<div class="container">
    <h2>Employees</h2>
    <div class="pb-2">
        <a asp-controller="Employees" asp-action="Edit"
           type="button" class="btn btn-primary">
            Create new employee
        </a>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Middle Name</th>
                <th>Hiring Date</th>
                <th>Position</th>
                <th>Company Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Id</td>
                <td>@employee.LastName</td>
                <td>@employee.FirstName</td>
                <td>@employee.MiddleName</td>
                <td>@employee.HiringDate.Date</td>
                <td>@employee.Position.ToString()</td>
                <td>@employee.Company.Name</td>
                <td>
                    <div class="row col-12">
                        <div class="col-6">
                            <a asp-controller="Employees" asp-action="Edit"
                               asp-route-id="@employee.Id" type="button" class="btn btn-success">
                                Edit
                            </a>
                        </div>
                        <div class="pl-2 col-6">
                            <a asp-controller="Employees" asp-action="Delete"
                               asp-route-id="@employee.Id" type="button" class="btn btn-dark">
                                Delete
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

ProjectZ/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectZ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectZ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectZ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProjectZ - <a asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>